### ISSUE TITLE
Doesn't work on HyperOS

### ISSUE THREAD

**Issue by BlueGradientHorizon** [Hepolise/VolumeKeyTrackControlModule#42]
POCO F5 (`marble`)
HyperOS 1.0.6.0.UMRMIXM stock (A14)
KernelSU LKM mode

In LSPosed logs:
```
VMhT.M.Hh.aYu.J.xtnRne.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.android.server.policy.PhoneWindowManager
	at VMhT.M.Hh.aYu.J.xtnRne.XposedHelpers.findClass(Unknown Source:12)
	at VMhT.M.Hh.aYu.J.xtnRne.XposedHelpers.findAndHookMethod(SourceFile:6)
	at ru.hepolise.volumekeytrackcontrolmodule.VolumeControlModule.init(Unknown Source:20)
	at ru.hepolise.volumekeytrackcontrolmodule.VolumeControlModule.handleLoadPackage(Unknown Source:12)
	at VMhT.M.Hh.aYu.J.xtnRne.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at VMhT.M.Hh.aYu.J.xtnRne.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at VMhT.M.Hh.aYu.J.xtnRne.callbacks.XCallback.callAll(Unknown Source:26)
	at h0.a(Unknown Source:320)
	at java.lang.reflect.Method.invoke(Native Method)
	at J.callback(Unknown Source:253)
	at LSPHooker_.createOrUpdateClassLoaderLocked(Unknown Source:11)
	at android.app.LoadedApk.getClassLoader(LoadedApk.java:1141)
	at android.app.ContextImpl.getClassLoader(ContextImpl.java:510)
	at android.app.ActivityThread.installProvider(ActivityThread.java:8314)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7836)
	at android.app.ActivityThread.installSystemProviders(ActivityThread.java:8527)
	at com.android.server.am.ContentProviderHelper.installSystemProviders(ContentProviderHelper.java:1483)
	at com.android.server.SystemServer.startOtherServices(SystemServer.java:1641)
	at com.android.server.SystemServer.run(SystemServer.java:1008)
	at com.android.server.SystemServer.main(SystemServer.java:724)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:991)
Caused by: java.lang.ClassNotFoundException: com.android.server.policy.PhoneWindowManager
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:607)
	at q.a(Unknown Source:16)
	at VMhT.M.Hh.aYu.J.xtnRne.XposedHelpers.findClass(Unknown Source:4)
	at VMhT.M.Hh.aYu.J.xtnRne.XposedHelpers.findAndHookMethod(SourceFile:6) 
	at ru.hepolise.volumekeytrackcontrolmodule.VolumeControlModule.init(Unknown Source:20) 
	at ru.hepolise.volumekeytrackcontrolmodule.VolumeControlModule.handleLoadPackage(Unknown Source:12) 
	at VMhT.M.Hh.aYu.J.xtnRne.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2) 
	at VMhT.M.Hh.aYu.J.xtnRne.callbacks.XC_LoadPackage.call(Unknown Source:6) 
	at VMhT.M.Hh.aYu.J.xtnRne.callbacks.XCallback.callAll(Unknown Source:26) 
	at h0.a(Unknown Source:320) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at J.callback(Unknown Source:253) 
	at LSPHooker_.createOrUpdateClassLoaderLocked(Unknown Source:11) 
	at android.app.LoadedApk.getClassLoader(LoadedApk.java:1141) 
	at android.app.ContextImpl.getClassLoader(ContextImpl.java:510) 
	at android.app.ActivityThread.installProvider(ActivityThread.java:8314) 
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7836) 
	at android.app.ActivityThread.installSystemProviders(ActivityThread.java:8527) 
	at com.android.server.am.ContentProviderHelper.installSystemProviders(ContentProviderHelper.java:1483) 
	at com.android.server.SystemServer.startOtherServices(SystemServer.java:1641) 
	at com.android.server.SystemServer.run(SystemServer.java:1008) 
	at com.android.server.SystemServer.main(SystemServer.java:724) 
	at java.lang.reflect.Method.invoke(Native Method) 
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561) 
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:991) 
```

**Comment by Hepolise** [comment]
Can you please attach your services.jar?

**Comment by BlueGradientHorizon** [comment]
I'm currently having an issue uploading a file as an attachment to comment, leaving a link to gdrive, [link](https://drive.google.com/file/d/1Eav19e8YO6aiodOB4kLOeBovAlPeSSsz/view?usp=sharing)

**Comment by Hepolise** [comment]
Can you check this version?
[Build Artifacts.zip](https://github.com/user-attachments/files/17056795/Build.Artifacts.zip)

**Comment by BlueGradientHorizon** [comment]
I'm getting the same `ClassNotFoundException` on `com.android.server.policy.PhoneWindowManager` (`VolumeControlModule.kt:29`).

**Comment by BlueGradientHorizon** [comment]
Oh, yeah, module seems to be functioning correctly. It is my fault for not testing the actual behavior and only looking into logs, sorry. Thank you. But then why are exceptions still being thrown? Maybe they are thrown when the system is not fully booted yet? I'm not familiar with how LSPosed works and loads modules.

**Comment by Hepolise** [comment]
There is no boot stages in XPosed, it may be wrong process. I will try to figure this out and then release the update. Thank you for your help!
